# Napisz poniżej funkcję, która wyprintuje Twoje imię i nazwisko: 

# Indeksowanie, wycinanie, iterowanie - Indexing, Slicing and Iterating

### Stwórz liste sześcianów liczb od 0 do 9

In [33]:
import numpy as np
x = np.array([0,1,2,3,4,5,6,7,8,9])**3
x


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### wybierz z listy zaznaczone elementy

[ 0, 1, **8**, **27**, **64**, 125, 216, 343, 512, 729]

    

In [34]:
x[2:5]

array([ 8, 27, 64], dtype=int32)

[ **0**, 1, **8**, 27, **64**, 125, 216, 343, 512, 729]

In [35]:
x[:5:2]

array([ 0,  8, 64], dtype=int32)

### przekształć by otrzymać wynik

[-1000, 1,  -1000, 27, -1000,   125,   216,   343,   512, 729]

In [36]:
x[:5:2] = -1000
x



array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

### Odwróć listę

In [37]:
x[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

### Sprawdź typ 

In [38]:
x.dtype

dtype('int32')

### W pętli for wyprintuj dla każdego elementu pierwiastek sześcienny z elementy

In [41]:
for i in x:
    print(i**(1/3))
    
x **(1/3.)

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


c:\users\kurs\pycharmprojects\python_bootcamp\venv\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  
c:\users\kurs\pycharmprojects\python_bootcamp\venv\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in power
  after removing the cwd from sys.path.


array([nan,  1., nan,  3., nan,  5.,  6.,  7.,  8.,  9.])

### Stwórz macierz 10x10 z kwadratami liczb od 1 do 100

In [45]:
y = np.arange(1,101).reshape(10,10)** 2
print(y)


[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


### Stwórz macierz 5x5 gdzie na krawędziach będą 0 a w środku 1

In [64]:
x = np.zeros((5,5))
x[1:-1,1:-1] = 10
x

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0., 10., 10., 10.,  0.],
       [ 0., 10., 10., 10.,  0.],
       [ 0., 10., 10., 10.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

### Stwórz tabliczkę mnożenia liczb od 0 do 9 w postaci dwuwymiarowej macierzy

In [76]:
x =np.arange(10) * np.array([0,1,2,3,4,5,6,7,8,9]).reshape(10,1)
x

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [77]:
!dir

 Wolumin w stacji C nie ma etykiety.
 Numer seryjny woluminu: 8C5A-2D9C

 Katalog: C:\Users\kurs\PycharmProjects\python_bootcamp\Science

2019-01-09  19:38    <DIR>          .
2019-01-09  19:38    <DIR>          ..
2019-01-07  20:23    <DIR>          .ipynb_checkpoints
2019-01-07  19:53                 0 gff
2019-01-07  20:15    <DIR>          images
2019-01-09  19:38            11˙410 numpy_bootcamp_zadania.ipynb
2019-01-09  18:26             3˙974 Untitled.ipynb
               3 plik(˘w)             15˙384 bajt˘w
               4 katalog(˘w)  16˙837˙771˙264 bajt˘w wolnych


## Zad 2  Przekształć wczytane obrazki w opisany sposób 

In [ ]:
# !pip install opencv-python
import matplotlib.pyplot as plt

In [ ]:
%matplotlib inline

In [ ]:
# import matplotlib.image as mpimg
im1 = mpimg.imread('images/monkey.png')


In [ ]:
import cv2
im2 = cv2.imread("images/index.jpeg")


In [ ]:
im1.shape

In [ ]:
im2.shape

In [ ]:
plt.imshow(im1)

In [ ]:
plt.imshow(im2)

### stwórz wycinek -  spróbuj wybrać twarz

### wybierz jeden kolor

### Obrót o wskazaną liczbę stopni 

wykorzystaj ndimage.rotate ze scipy

### Czarno biały filtr

### Rozmazanie

wykorzystaj `ndimage.gaussian_filter`

Wyślij mi to proszę na adres: korzeniewski@gmail.com, w tytule wpisz "Ćwiczenia z NumPy"